system_message: &sys_msg 'You will be summarizing the Eligibility Criteria section of a clinical trial protocol document. Note that in the Eligibility Criteria section, the suffix "(inclusion--- t)" denotes that the line describes an inclusion criterion, and "(inclusion--- f)" denotes an exclusion criterion.'

# https://platform.openai.com/docs/api-reference/chat/create
chat:
  temperature: 0.1
  top_p: 1
  max_tokens: 800
  stop: null
  stream: false

# https://learn.microsoft.com/en-us/azure/ai-services/openai/references/azure-search?tabs=python#parameters
search:
  fieldsMapping: {}
  filter: null
  inScope: true
  queryType: simple
  # Provide embeddingDeploymentName when using a vector queryType
  # embeddingDeploymentName: embeddings
  roleInformation: *sys_msg
  semanticConfiguration: default
  strictness: 3
  topNDocuments: 5
