system_message: &sys_msg "You are an AI assistant that helps people extract information from documents."

# https://platform.openai.com/docs/api-reference/chat/create
chat:
  temperature: 0.2
  top_p: 1
  max_tokens: 800
  stop: null
  stream: false

# https://learn.microsoft.com/en-us/azure/ai-services/openai/references/azure-search?tabs=python#parameters
search:
  fieldsMapping: {}
  filter: null
  inScope: true
  # https://learn.microsoft.com/en-us/azure/ai-services/openai/references/azure-search?tabs=python#query-type
  queryType: vectorSemanticHybrid
  # Provide embeddingDeploymentName when using a vector queryType
  embeddingDeploymentName: embeddings
  roleInformation: *sys_msg
  semanticConfiguration: default
  # NOTE: If the answer is "The requested information is not available in the retrieved data. Please try another query or topic."
  #       try adjusting the strictness.
  strictness: 2
  topNDocuments: 5
